config/routes.rb
Rails.application.routes.draw do
  resources :cupons do   # define as rotas altomatica de restful para o recurso cupons "que é a estrutura mvc gerada pelo scaffold cupons"
          member do     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
            get :validar 
          end
  end 
    root "cupons#index" #root define a página inicial (home#index) do projeto reails


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cupon.rb
class Cupon < ApplicationRecord
     attr_accessor :nova_data_de_criacao 
    def valido?  # esse metodo verifica se o cupom esta valido
       return false if validade.nil?

        horas_passadas = ((Time.current - created_at) / 1.hour).round # subtrai a data atual da data de criação, e arredonda para baixo ou para cima
        horas_validade = validade * 24

        horas_passadas <= horas_validade
        
        
    end

     def dias_restantes # esse metodo retorna quantos dias restam para o cupom expirar
        return 0 if validade.nil?

        horas_passadas = ((Time.current - created_at) / 1.hour).round
        horas_validade = validade * 24

        horas_restantes = horas_validade - horas_passadas
        dias = (horas_restantes / 24.0).ceil

        dias > 0 ? dias : 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cupons_controller.rb
class CuponsController < ApplicationController
  before_action :set_cupon, only: %i[ show edit update destroy ]

  # GET /cupons or /cupons.json
  def index
    @cupons = Cupon.all
  end

  # GET /cupons/1 or /cupons/1.json
  def show
  end

  # GET /cupons/new
  def new
    @cupon = Cupon.new
  end

  # GET /cupons/1/edit
  def edit
  end

  # POST /cupons or /cupons.json
  def create
    @cupon = Cupon.new(cupon_params)

    respond_to do |format|
      if @cupon.save
        format.html { redirect_to @cupon, notice: "Cupon was successfully created." }
        format.json { render :show, status: :created, location: @cupon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cupon.errors, status: :unprocessable_entity }
      end
    end
  end


  def validar 
    @cupon = Cupon.find(params[:id])
    if @cupon.valido?
      flash[:notice] = "Cupon Valido"
      flash[:valido_id] = @cupon.id
      flash[:valido] = true
    else
      flash[:alert] = "Cupon Expirado"
      flash[:valido_id] = @cupon.id
      flash[:valido] = false
    end

    redirect_to cupon_path

  end

  # PATCH/PUT /cupons/1 or /cupons/1.json
  def update
    respond_to do |format|
      if @cupon.update(cupon_params)
        nova_data = params[:cupon][:nova_data_de_criacao] # pega a nova data de criação que atualizara a data de criação do cupon
        if nova_data.present? # se a nova data estiver presente existir
          @cupon.update_column(:created_at, Date.parse(nova_data).beginning_of_day) # converte a nova data para o formato de data do campo created_at da tabela  cupons
        end

        format.html { redirect_to @cupon, notice: "Cupon was successfully updated." }
        format.json { render :show, status: :ok, location: @cupon }

      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cupons/1 or /cupons/1.json
  def destroy
    @cupon.destroy!

    respond_to do |format|
      format.html { redirect_to cupons_path, status: :see_other, notice: "Cupon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cupon
      @cupon = Cupon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cupon_params
      params.require(:cupon).permit(:description, :url_image, :code_id, :validade, :nova_data_de_criacao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cupons_helper.rb
module CuponsHelper
end

app/views/cupons/_cupon.html.erb
<div class="cupom__container">
 
    <div id="<%= dom_id cupon %>" class="card__container">
      <p>
        <%= cupon.description %>
      </p>
     
       
        <%= image_tag cupon.url_image, class:"image__container" %>


      <p>
        <strong>Cupom:</strong>
        <%= cupon.code_id %>
      </p>

    <% if flash[:valido_id] == cupon.id %>
      <% if flash[:valido] %>
        <p style="color: green"><strong>Cupom válido ✅</strong></p>
      <% else %>
        <p style="color: red"><strong>Cupom expirado ❌</strong></p>
      <% end %>
    <% else %>
      <p>
        <strong>Validade:</strong>
        <%= cupon.validade %> Dias
      </p>
    <% end %>

       <%# o codigo abaixo mostra uma contagem regressiva dos diaas de validades dos cupons %> 
      <% if cupon.valido? %> 
        <p style="color: green;">Válido por <strong><%= cupon.dias_restantes %></strong> dia(s)</p>
      <% else %>
        <p style="color: red;">Cupom expirado</p>
      <% end %>





  
    <%= button_to "Validar Cupom", validar_cupon_path(cupon), method: :get, class: "btn btn-primary" %>

    </div>
    <p>
      <%= link_to "Show this cupon", cupon %>
    </p>
</div>

app/views/cupons/_form.html.erb
<%= form_with(model: cupon) do |form| %>
  <% if cupon.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cupon.errors.count, "error") %> prohibited this cupon from being saved:</h2>

      <ul>
        <% cupon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :url_image, style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div>
    <%= form.label :code_id, style: "display: block" %>
    <%= form.text_field :code_id %>
  </div>

  <div class="field">
    <%= form.label :validade, "Validade (dias)" , style: "display: block" %>
    <%= form.number_field :validade, min: 1 %>
  </div>

  <% if form.object.persisted? %>
    <div class="field">
      <%= form.label :nova_data_de_criacao, "Nova data de criação" %><br>
      <%= form.date_field :nova_data_de_criacao %>
      <p style="font-size: 0.8rem; color: gray;">(Deixe vazio se não quiser alterar)</p>
    </div>
  <% end %>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cupons/edit.html.erb
<h1>Editing cupon</h1>

<%= render "form", cupon: @cupon %>

<br>

<div>
  <%= link_to "Show this cupon", @cupon %> |
  <%= link_to "Back to cupons", cupons_path %>
</div>

app/views/cupons/index.html.erb
<div class="continer_index_cupons">
    <% if flash[:notice] %>
      <p style="color: green"><%= flash[:notice] %></p>
    <% end %>

   <% if flash[:alert] %>
      <p style="color: red"><%= flash[:alert] %></p>
    <% end %>

    <h1>Cupons</h1>
    <%= link_to "New cupon", new_cupon_path %>

    <div id="cupons" class="show__cupons__container">
      <% @cupons.each do |cupon| %>
        <%= render cupon %>
        


        
      <% end %>
    </div>

</div>

app/views/cupons/new.html.erb
<h1>New cupon</h1>

<%= render "form", cupon: @cupon %>

<br>

<div>
  <%= link_to "Back to cupons", cupons_path %>
</div>

app/views/cupons/show.html.erb
<% if flash[:notice] %>
  <p style="color: green"><%= flash[:notice] %></p>
<% end %>

<% if flash[:alert] %>
  <p style="color: red"><%= flash[:alert] %></p>
<% end %>


<div class="cupom_links_container">
<%= render @cupon %>


      <%= link_to "Edit this cupon", edit_cupon_path(@cupon) %> 
      <%= link_to "Back to cupons", cupons_path %>

      <%= button_to "Destroy this cupon", @cupon, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cupom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>